CREATE TABLE IF NOT EXISTS CLASSIFICATION (
    id SERIAL PRIMARY KEY,
    title VARCHAR(1000) NOT NULL,
    Authors VARCHAR(1000),
    DOI VARCHAR(255) NOT NULL,
    Open_Access BOOLEAN DEFAULT TRUE,
    Has_data BOOLEAN DEFAULT FALSE,
    DONE BOOLEAN DEFAULT FALSE,
    UNIQUE (DOI)
);

CREATE TABLE IF NOT EXISTS EXTRACTION (
    id SERIAL PRIMARY KEY,
    pid INTEGER REFERENCES CLASSIFICATION(id),
    URL VARCHAR(1000),
    done BOOLEAN DEFAULT FALSE,
    data_link VARCHAR(1000)
);