CREATE DATABASE IF NOT EXISTS ResearchDB;
USE ResearchDB;

CREATE TABLE IF NOT EXISTS CLASSIFICATION (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    Authors TEXT,
    DOI TEXT NOT NULL,
    Open_Access BOOLEAN DEFAULT TRUE,
    Organization TEXT,
    Country TEXT,
    Year INTEGER,
    Has_data BOOLEAN DEFAULT FALSE,
    DONE BOOLEAN DEFAULT FALSE,
    UNIQUE (DOI)
);

CREATE TABLE IF NOT EXISTS EXTRACTION (
    id SERIAL PRIMARY KEY,
    pid INTEGER REFERENCES CLASSIFICATION(id),
    URL VARCHAR(1000),
    source_website VARCHAR(20),
    done BOOLEAN DEFAULT FALSE,
    data_link VARCHAR(1000)
);